version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
     - dependency-name: "rsc.io/quote"
       versions: [ ">= 1.9.0" ]
  - package-ecosystem: "npm"
    directory: "/yarn"
    schedule:
      interval: "weekly"
